### ISSUE TITLE
Help with memory tuning for small embedded devices.

### ISSUE THREAD

**Issue by Andy2244** [namjaejeon/ksmbd-tools#134]
Hey i just found this: https://bugs.openwrt.org/index.php?do=details&task_id=2660

Maybe you can help which defaults we should tweak, to avoid this issue, while keeping good performance? I guess most are interested using cifsd as simple fileserver, so large file streaming is the main use case for us.

Lets assume cifsd has to work with 8/16 MB ram, what tweaks would we want?

**Comment by namjaejeon** [comment]
We should add smb2 max read, smb2 max write, cache read/trans buffers parameters in smb.conf to change default value. When installing cifsd package to target, smb.conf is also installed ?

**Comment by Andy2244** [comment]
> We should add smb2 max read, smb2 max write, cache read/trans buffers parameters in smb.conf to change default value. When installing cifsd package to target, smb.conf is also installed ?

Not really, we have our own default template i can add the value, yet your values look kinda "lavish" and not even samba4 uses such huge buffers. 
So my suggestion would be to setup some basic tests and reduce all values to its minimum and work from there and see which increased values actually helps performance?

For now i just need some "good" defaults for low memory devices, the issue suggested disabling `cache read buffers, cache trans buffers` and reducing smb2 max read, smb2 max write, smb2 max trans to something like 64-512k?

So i just need a basic idea which values are safe to lower and to which values, aka what we should use as defaults in out smb.conf.

**Comment by namjaejeon** [comment]
> Not really, we have our own default template i can add the values to, yet your default values look kinda "lavish" and not even samba4 uses such huge buffers.

These are default value(8MB) of samba4.
smb2 max read (G)
    Default: smb2 max read = 8388608 
smb2 max trans (G)
    Default: smb2 max trans = 8388608 

> So my suggestion would be to setup some basic tests and reduce all values to its minimum and work from there and see which increased values actually helps performance?

Yes, Increased values will show better performance.

Yes, I recommend to use the following setup for 8/16MB RAM device.
[global]
   smb2 max read = 64K
   smb2 max write = 64K
   smb2 max trans = 64K
   cache read buffers = no
   cache trans buffers = no

Thanks!

**Comment by Andy2244** [comment]
> These are default value(8MB) of samba4.
> smb2 max read (G)
> Default: smb2 max read = 8388608
> smb2 max trans (G)
> Default: smb2 max trans = 8388608

Fair enough, yet there is also this:

> Please note that the default is 8MiB, but it's limit is based on the smb2 dialect (64KiB for SMB == 2.0, 8MiB for SMB >= 2.1 with LargeMTU).

If i interpret this correctly, this means they still just use 64kib without LargeMTU, which is kinda rare in home/small business environments.

**Comment by namjaejeon** [comment]
Windows 7, 10(> SMB2.1) and samba have LargeMTU support by default. So I think that LargeMTU will work on connection between windows and samba4. Could you please share tcpdump(or wireshark dump) to check whether LargeMTU is enable on connection between samba4 and windows 10 ? If it is disable, samba may check system resource...

**Comment by Andy2244** [comment]
>  So I think that LargeMTU will work on connection between windows and samba4.

mhh last time i tried to get LargeMTU to work with ip4, it was mainly a router/switch problem, since most consumer grade routers/switches have no support for it or some buggy settings. Even Synology NAS have it disabled by default?
I'm also confused why its always explicitly listed as "SMB2 and Large MTU", while SMB3 is listed separately? Is this maybe a smb2 only feature and obsolete with smb3?

**Comment by namjaejeon** [comment]
I don't know how other device and target work.

No, SMB2 and SMB3 is compatible.(SMB1 is not compatible with SMB2/3). And You can think SMB3 = SMB2 + @. So LargeMTU can be worked on SMB3.
Okay, I will add the code that set max read/write size as 64K on SMB2/3 without LargeMTU.

But I's not sure that it help current issue...

**Comment by Andy2244** [comment]
ok, i was mainly wondering why the "tiny" cifsd runs into oom crashes, while samba4 does not. I mean cifsd might be used by other embedded device optimized distros as well, so optimizing it more for minimal memory usage by default, might be worth the effort.

**Comment by namjaejeon** [comment]
Agreed, I will check it more.
Thanks for your opinion.

**Comment by namjaejeon** [comment]
@Andy2244 Could you please provide packet dump between samba4 and windows 10 on your low-end device(8 or 16MB RAM) ? I checked samba code, but they just set 8MB with SMB3(windows 10).

**Comment by Andy2244** [comment]
Sure, but will be next year not at home anymore.
