### ISSUE TITLE
ksmbd.service.in

### ISSUE THREAD

**Issue by thomzieg** [namjaejeon/ksmbd-tools#183]
Hi, I think line 3 in ksmbd.service.in is not right, it should probably read
Requires=modprobe ksmbd

**Comment by atheik** [comment]
@thomzieg,

Your suggestion is not a valid value for the `Requires=` option. The current value of `modprobe@ksmbd.service` is correct. systemd v245 and later ship with `modprobe@.service`. The `ksmbd.service` unit file is installed automatically for those versions of systemd. What prompted this issue?

**Comment by thomzieg** [comment]
Hi sorry now I see the problem. I'm on Centos 7 with systemd v219 and no ksmbd.service unit. I guess this is the reason why building ksmbd-tools with systemd support also gives an error. Therefore, I will close this issue.

**Comment by atheik** [comment]
@thomzieg,

How are you building ksmbd-tools? If the build system does not have systemd v245 or later, then the build succeeds but `ksmbd.service` is not installed. Or, are you using `ksmbd-tools.spec` of this repository? The spec file does require systemd v245 or later at package-installation time.

**Comment by thomzieg** [comment]
I've tried to force it by --with-systemdsystemunitdir but ran into an error which looked like a bug in the Makefile. But with latest git even this error has vanished, and everything looks clean. 
I have now my own ksmbd.service file with
`ExecStartPre=-/sbin/modprobe ksmbd`
Thanks for following up.
